repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: mixed-line-ending
        name: Zapobieganie windowsowym końcom linii (CRLF -> LF)
        args: [--fix=lf]
        files: \.(sh|py|txt|md|yaml|yml)$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.0
    hooks:
      - id: ruff
        args: [--fix, --config=backend/pyproject.toml]
      - id: ruff-format
        args: [--config=backend/pyproject.toml]

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: backend\.venv\Scripts\mypy.exe backend
        language: system
        types: [python]
        pass_filenames: false

  - repo: local
    hooks:
      - id: bandit
        name: bandit
        entry: powershell -Command "Set-Location backend; bandit -r app/ -ll"
        language: system
        types: [python]
        pass_filenames: false

  - repo: local
    hooks:
      - id: commitlint
        name: commitlint
        entry: commitlint --edit
        language: system
        stages: [commit-msg]
