[project]
name = "cv-ai-matcher"
version = "0.1.0"
description = "AI powered CV matching system using LLMs"
requires-python = ">=3.11"

dependencies = [

    # Web Framework & Core
    "fastapi",
    "uvicorn",
    "pydantic",
    "pydantic-settings",
    "python-dotenv",
    "python-multipart",
    "aiofiles",
    "pdfplumber",
    "pymupdf",
    "pytesseract",
    "pillow",
    "python-magic-bin; sys_platform == 'win32'",
    "python-magic; sys_platform != 'win32'",
    "sqlmodel>=0.0.22",
    "asyncpg",
    "pdf2image",
    "psycopg2-binary",
    "ftfy",
    "regex",
    "phonenumbers",
    "dateparser",
    "flashtext",
    "httpx",
]

[project.optional-dependencies]
dev = [
    "ruff",
    "black",
    "mypy",
    "alembic",
    "pre-commit",
    "loguru",
    "mkdocs",
    "mkdocs-material",
    "mkdocstrings[python]",
    "pydeps",
    "pylint",
    "graphviz",
    "pytest",
    "pytest-dotenv",
    "pytest-asyncio",
    "pytest-mock",
    "freezegun",
    "radon",
    "cohesion",
    "bandit"
]


[tool.ruff]
line-length = 88
target-version = "py311"

[tool.ruff.lint]
select = ["E", "F", "I"]
fixable = ["ALL"]
ignore = ["E501"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"


[tool.black]
line-length = 88
target-version = ["py311"]


[tool.mypy]
python_version = "3.11"
strict = true
ignore_missing_imports = true
warn_return_any = true
warn_unused_configs = true

[[tool.mypy.overrides]]
module = "magic.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "regex.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "pytesseract.*"
ignore_missing_imports = true


[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
filterwarnings = "ignore::DeprecationWarning"

env_files = [
    ".env.test"
]

[tool.radon]
cc_min = "B"
cc_sort = "score"
show_complexity = true
show_closures = true
color = true
ignore = [
    ".venv",
    "venv",
    "tests",
    "uploads",
    "logs",
    "__pycache__"
]
exclude = "**/test_*.py|**/__pycache__/*"


[tool.setuptools.packages.find]
include = ["app"]
exclude = ["uploads"]
